version: '2.2'
services:
  mysql:
    image: mysql:5.7.25
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=app
      - MYSQL_USER=kevin
      - MYSQL_PASSWORD=test123
    restart: always
    command: --init-file /data/mysql/init.sql
    volumes:
        - /data/mysql
        - ./init.sql:/data/mysql/init.sql
    ports:
      - 4402:3306
  spring-boot-jpa:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
